#ifdef _MSC_VER
#pragma warning(push)
#pragma warning(disable: 4996)
#pragma warning(disable: 4819)
#endif
#ifdef AVABM_USE_FULL_TORCH_EXTENSION_HEADER
#include <torch/extension.h>
#elif defined(__has_include)
#if __has_include(<torch/types.h>) && __has_include(<torch/csrc/utils/pybind.h>)
#include <torch/types.h>
#include <torch/csrc/utils/pybind.h>
#else
#include <torch/extension.h>
#endif
#else
#include <torch/types.h>
#include <torch/csrc/utils/pybind.h>
#endif
#include <ATen/cuda/CUDAContext.h>
#include <c10/cuda/CUDAException.h>
#include <c10/cuda/CUDAGuard.h>
#include <cuda_runtime.h>
#ifdef _MSC_VER
#pragma warning(pop)
#endif
#include <cmath>
#include <cstdint>
#include <limits>
constexpr int MAX_CONFLICT_LANES_BINDING = 8; constexpr int RES_HORIZON_SLOTS_BINDING = 16; constexpr int64_t METRICS_SIZE_MIN = 112;
#ifndef CONTACT_RESOLVE_PASSES
#define CONTACT_RESOLVE_PASSES 9
#endif
#ifndef AVABM_PERSISTENT_START_GRID
#define AVABM_PERSISTENT_START_GRID 1
#endif
#ifndef AVABM_ECS_PERSISTENT_PERCEPTION_GRID_REUSE
#define AVABM_ECS_PERSISTENT_PERCEPTION_GRID_REUSE 1
#endif
#ifndef AVABM_SPAWN_GRID_INSERT_FASTPATH
#define AVABM_SPAWN_GRID_INSERT_FASTPATH 1
#endif
#ifndef AVABM_ROUTE_REPAIR_INTERVAL
#define AVABM_ROUTE_REPAIR_INTERVAL 1
#endif
#ifndef AVABM_FAST_PHYSICS_MODE
#define AVABM_FAST_PHYSICS_MODE 0
#endif
#ifndef AVABM_SPAWN_OVERLAP_INTERVAL
#define AVABM_SPAWN_OVERLAP_INTERVAL 1
#endif
#ifndef AVABM_CONTACT_INTERVAL
#define AVABM_CONTACT_INTERVAL 1
#endif
struct ECSArrays { int* alive; float* x; float* y; float* s; float* speed; float* accel; float* heading; float* steer_angle; float* length; float* width; int* driver_type; float* reaction_time; float* min_gap; float* aggressiveness; float* politeness; float* risk_tolerance; float* comfort_decel; float* desired_speed_factor; int* lane_id; int* route_id;
int* route_pos; float* entry_time; int* vehicle_state; int* connector_from_lane; int* connector_to_lane; float* connector_s; float* connector_length; int* lane_change_active; int* lane_change_from_lane; int* lane_change_to_lane; float* lane_change_t; float* lane_change_duration; float* lc_cooldown; int* turn_signal; float* turn_signal_time; };
struct RoadNetwork { const float* lane_length; const float* lane_start_x; const float* lane_start_y; const float* lane_end_x; const float* lane_end_y; const float* lane_speed_limit; const int* lane_start_node; const int* lane_end_node; const int* left_lane; const int* right_lane; const int* route_offsets; const int* route_lanes; const int* route_turns;
int num_lanes; int num_nodes; int num_routes; }; struct Signals { const int* signal_node; const int* signal_turn; const float* signal_cycle; const float* signal_green_start; const float* signal_green_end; const float* signal_yellow_start; const float* signal_yellow_end; int num_signals; }; struct SpatialGrid { int* cell_head; int* cell_next; int* cell_epoch;
int epoch; int* lane_cell_head; int* lane_cell_next; int lane_cells_per_lane; float min_x; float min_y; float cell_size; int width; int height; }; struct SpawnConfig { float* spawn_accumulator; const float* demand_vps; const float* demand_profile_vps; const int* demand_profile_has; const int* spawn_lane; const int* spawn_route; int* spawn_alloc_cursor;
int num_spawn_points; int demand_profile_slots; float demand_profile_slot_seconds; float av_penetration; }; struct PerceptionSoA { float* front_gap; float* front_speed; float* front_s; float* front_length; int* front_lane; float* target_front_gap; float* target_front_speed; float* target_rear_gap; float* target_rear_speed; }; struct DecisionSoA {
float* desired_speed; float* target_accel; int* wants_lane_change; int* lane_change_target; int* wants_connector; int* connector_target_lane; int* should_exit; };
extern "C" void launch_step_cuda_ecs(ECSArrays ecs,RoadNetwork road,Signals signals,SpatialGrid grid,SpawnConfig spawn,PerceptionSoA perception,DecisionSoA decision,int* reservation_table,uint32_t* rng_state,float* metrics,int* active_ids,int* active_count,int* lane_active_ids,int* lane_active_count,int* connector_active_ids,int* connector_active_count,int initial_grid_valid,float current_time,float dt,int max_entities,int step_index,cudaStream_t stream);
extern "C" void register_render_vbo_cuda(unsigned int vbo); extern "C" void set_vehicle_texture_render_cuda(int enabled); extern "C" void launch_render_vbo_cuda_ecs(ECSArrays ecs,int max_entities,const int* active_ids,const int* active_count,int* render_count,int* previous_render_count,cudaStream_t stream,int clear_tail_for_full_draw);
extern "C" void launch_render_vbo_interpolated_cuda_ecs(ECSArrays prev_ecs,ECSArrays curr_ecs,int max_entities,const int* active_ids,const int* active_count,int* render_count,int* previous_render_count,cudaStream_t stream,int clear_tail_for_full_draw,float alpha); extern "C" void unregister_render_vbo_cuda();
#define CHECK_CUDA(x) TORCH_CHECK((x).is_cuda(), #x " must be CUDA tensor")
#define CHECK_CONTIGUOUS(x) TORCH_CHECK((x).is_contiguous(), #x " must be contiguous")
#define CHECK_INPUT(x) \
CHECK_CUDA(x);     \
CHECK_CONTIGUOUS(x)
#define CHECK_FLOAT32(x) TORCH_CHECK((x).scalar_type() == torch::kFloat32, #x " must be float32")
#define CHECK_INT32(x) TORCH_CHECK((x).scalar_type() == torch::kInt32, #x " must be int32")
static inline void check_same_cuda_device(const torch::Tensor& t,const char* name,const torch::Tensor& ref,const char* ref_name) { TORCH_CHECK(t.is_cuda(), name, " must be CUDA tensor"); TORCH_CHECK(ref.is_cuda(), ref_name, " must be CUDA tensor");
TORCH_CHECK(t.device() == ref.device(),name," must be on the same CUDA device as ",ref_name,"; got ",t.device()," vs ",ref.device()); } static inline void check_1d_tensor(const torch::Tensor& t,const char* name,int64_t expected_numel,c10::ScalarType dtype,const torch::Tensor& ref_device_tensor) { TORCH_CHECK(t.dim() == 1, name, " must be 1D");
TORCH_CHECK(t.numel() == expected_numel, name, ".numel() must equal ", expected_numel); TORCH_CHECK(t.scalar_type() == dtype, name, " has wrong dtype"); TORCH_CHECK(t.is_cuda(), name, " must be CUDA tensor"); TORCH_CHECK(t.is_contiguous(), name, " must be contiguous"); check_same_cuda_device(t, name, ref_device_tensor, "s"); }
static inline void check_agent_float_tensor(const torch::Tensor& t,const char* name,int64_t max_agents,const torch::Tensor& ref_device_tensor) { check_1d_tensor(t, name, max_agents, torch::kFloat32, ref_device_tensor); }
static inline void check_agent_int_tensor(const torch::Tensor& t,const char* name,int64_t max_agents,const torch::Tensor& ref_device_tensor) { check_1d_tensor(t, name, max_agents, torch::kInt32, ref_device_tensor); } static inline void check_lane_float_tensor(const torch::Tensor& t,const char* name,int64_t num_lanes,const torch::Tensor& ref_device_tensor) {
check_1d_tensor(t, name, num_lanes, torch::kFloat32, ref_device_tensor); } static inline void check_lane_int_tensor(const torch::Tensor& t,const char* name,int64_t num_lanes,const torch::Tensor& ref_device_tensor) { check_1d_tensor(t, name, num_lanes, torch::kInt32, ref_device_tensor); }
static inline void check_spawn_float_tensor(const torch::Tensor& t,const char* name,int64_t num_spawn_points,const torch::Tensor& ref_device_tensor) { check_1d_tensor(t, name, num_spawn_points, torch::kFloat32, ref_device_tensor); }
static inline void check_spawn_int_tensor(const torch::Tensor& t,const char* name,int64_t num_spawn_points,const torch::Tensor& ref_device_tensor) { check_1d_tensor(t, name, num_spawn_points, torch::kInt32, ref_device_tensor); }
static inline void check_signal_int_tensor(const torch::Tensor& t,const char* name,int64_t num_signals,const torch::Tensor& ref_device_tensor) { check_1d_tensor(t, name, num_signals, torch::kInt32, ref_device_tensor); }
static inline void check_signal_float_tensor(const torch::Tensor& t,const char* name,int64_t num_signals,const torch::Tensor& ref_device_tensor) { check_1d_tensor(t, name, num_signals, torch::kFloat32, ref_device_tensor); }
static inline void check_node_int_tensor(const torch::Tensor& t,const char* name,int64_t num_nodes,const torch::Tensor& ref_device_tensor) { check_1d_tensor(t, name, num_nodes, torch::kInt32, ref_device_tensor); } static inline void check_int64_to_int_range(int64_t v, const char* name) {
TORCH_CHECK(v >= static_cast<int64_t>(std::numeric_limits<int>::min()) && v <= static_cast<int64_t>(std::numeric_limits<int>::max()),name," exceeds int range"); } static inline void check_nonnegative_int64_to_int_range(int64_t v, const char* name) { TORCH_CHECK(v >= 0, name, " must be non-negative"); check_int64_to_int_range(v, name); }
static inline ECSArrays make_ecs_arrays(torch::Tensor s,torch::Tensor x,torch::Tensor y,torch::Tensor speed,torch::Tensor accel,torch::Tensor heading,torch::Tensor steer_angle,torch::Tensor vehicle_length,torch::Tensor vehicle_width,torch::Tensor reaction_time,torch::Tensor min_gap,torch::Tensor lane_id,torch::Tensor active,torch::Tensor driver_type,torch::Tensor route_id,torch::Tensor route_pos,torch::Tensor vehicle_state,torch::Tensor connector_from_lane,torch::Tensor connector_to_lane,torch::Tensor connector_s,torch::Tensor connector_length,torch::Tensor lane_change_active,torch::Tensor lane_change_from_lane,torch::Tensor lane_change_to_lane,torch::Tensor lane_change_t,torch::Tensor lane_change_duration,torch::Tensor aggressiveness,torch::Tensor politeness,torch::Tensor risk_tolerance,torch::Tensor comfort_decel,torch::Tensor desired_speed_factor,torch::Tensor lc_cooldown,torch::Tensor turn_signal,torch::Tensor turn_signal_time,torch::Tensor entry_time) {
ECSArrays ecs{}; ecs.alive = active.data_ptr<int>(); ecs.x = x.data_ptr<float>(); ecs.y = y.data_ptr<float>(); ecs.s = s.data_ptr<float>(); ecs.speed = speed.data_ptr<float>(); ecs.accel = accel.data_ptr<float>(); ecs.heading = heading.data_ptr<float>(); ecs.steer_angle = steer_angle.data_ptr<float>(); ecs.length = vehicle_length.data_ptr<float>();
ecs.width = vehicle_width.data_ptr<float>(); ecs.driver_type = driver_type.data_ptr<int>(); ecs.reaction_time = reaction_time.data_ptr<float>(); ecs.min_gap = min_gap.data_ptr<float>(); ecs.aggressiveness = aggressiveness.data_ptr<float>(); ecs.politeness = politeness.data_ptr<float>(); ecs.risk_tolerance = risk_tolerance.data_ptr<float>();
ecs.comfort_decel = comfort_decel.data_ptr<float>(); ecs.desired_speed_factor = desired_speed_factor.data_ptr<float>(); ecs.lane_id = lane_id.data_ptr<int>(); ecs.route_id = route_id.data_ptr<int>(); ecs.route_pos = route_pos.data_ptr<int>(); ecs.entry_time = entry_time.data_ptr<float>(); ecs.vehicle_state = vehicle_state.data_ptr<int>();
ecs.connector_from_lane = connector_from_lane.data_ptr<int>(); ecs.connector_to_lane = connector_to_lane.data_ptr<int>(); ecs.connector_s = connector_s.data_ptr<float>(); ecs.connector_length = connector_length.data_ptr<float>(); ecs.lane_change_active = lane_change_active.data_ptr<int>(); ecs.lane_change_from_lane = lane_change_from_lane.data_ptr<int>();
ecs.lane_change_to_lane = lane_change_to_lane.data_ptr<int>(); ecs.lane_change_t = lane_change_t.data_ptr<float>(); ecs.lane_change_duration = lane_change_duration.data_ptr<float>(); ecs.lc_cooldown = lc_cooldown.data_ptr<float>(); ecs.turn_signal = turn_signal.data_ptr<int>(); ecs.turn_signal_time = turn_signal_time.data_ptr<float>(); return ecs; }
struct StepTempBufferCache { int64_t max_agents = -1; int device_index = -9999; torch::Tensor perception_front_gap; torch::Tensor perception_front_speed; torch::Tensor perception_front_s; torch::Tensor perception_front_length; torch::Tensor perception_front_lane; torch::Tensor perception_target_front_gap; torch::Tensor perception_target_front_speed;
torch::Tensor perception_target_rear_gap; torch::Tensor perception_target_rear_speed; torch::Tensor decision_desired_speed; torch::Tensor decision_target_accel; torch::Tensor decision_wants_lane_change; torch::Tensor decision_lane_change_target; torch::Tensor decision_wants_connector; torch::Tensor decision_connector_target_lane;
torch::Tensor decision_should_exit; int64_t world_cells = -1; int grid_epoch = 1; bool persistent_grid_valid = false; torch::Tensor active_ids; torch::Tensor active_count; torch::Tensor lane_active_ids; torch::Tensor lane_active_count; torch::Tensor connector_active_ids; torch::Tensor connector_active_count; torch::Tensor spawn_alloc_cursor;
torch::Tensor render_count; torch::Tensor render_previous_count; torch::Tensor grid_cell_epoch; bool valid_for(int64_t n, int64_t cells, const torch::Tensor& ref) const {
return max_agents == n && world_cells == cells && device_index == ref.device().index() && perception_front_gap.defined() && perception_front_gap.is_cuda() && perception_front_gap.device() == ref.device() && active_ids.defined() && active_count.defined() && lane_active_ids.defined() && lane_active_count.defined() && connector_active_ids.defined() && connector_active_count.defined() && spawn_alloc_cursor.defined() && spawn_alloc_cursor.is_cuda() && spawn_alloc_cursor.device() == ref.device() && render_count.defined() && render_previous_count.defined() && render_previous_count.is_cuda() && render_previous_count.device() == ref.device() && grid_cell_epoch.defined();
} void ensure(int64_t n, int64_t cells, const torch::Tensor& ref) { if (valid_for(n, cells, ref)) return; auto float_opts = ref.options().dtype(torch::kFloat32); auto int_opts = ref.options().dtype(torch::kInt32); perception_front_gap = torch::empty({n}, float_opts); perception_front_speed = torch::empty({n}, float_opts);
perception_front_s = torch::empty({n}, float_opts); perception_front_length = torch::empty({n}, float_opts); perception_front_lane = torch::empty({n}, int_opts); perception_target_front_gap = torch::empty({n}, float_opts); perception_target_front_speed = torch::empty({n}, float_opts); perception_target_rear_gap = torch::empty({n}, float_opts);
perception_target_rear_speed = torch::empty({n}, float_opts); decision_desired_speed = torch::empty({n}, float_opts); decision_target_accel = torch::empty({n}, float_opts); decision_wants_lane_change = torch::empty({n}, int_opts); decision_lane_change_target = torch::empty({n}, int_opts); decision_wants_connector = torch::empty({n}, int_opts);
decision_connector_target_lane = torch::empty({n}, int_opts); decision_should_exit = torch::empty({n}, int_opts); active_ids = torch::empty({n}, int_opts); active_count = torch::zeros({1}, int_opts); lane_active_ids = torch::empty({n}, int_opts); lane_active_count = torch::zeros({1}, int_opts); connector_active_ids = torch::empty({n}, int_opts);
connector_active_count = torch::zeros({1}, int_opts); spawn_alloc_cursor = torch::zeros({1}, int_opts); render_count = torch::empty({1}, int_opts); render_previous_count = torch::full({1}, static_cast<int>(n), int_opts); grid_cell_epoch = torch::zeros({cells}, int_opts); max_agents = n; world_cells = cells; device_index = ref.device().index();
grid_epoch = 1; persistent_grid_valid = false; } }; static thread_local StepTempBufferCache g_step_temp_buffers; static inline bool avabm_interval_runs_for_step(int step_index, int interval) { return interval <= 1 || (step_index % interval) == 0; } static inline bool avabm_route_repair_runs_for_step(int step_index) {
#if AVABM_FAST_PHYSICS_MODE
return avabm_interval_runs_for_step(step_index, AVABM_ROUTE_REPAIR_INTERVAL);
#else
(void)step_index; return true;
#endif
} static inline bool avabm_spawn_overlap_runs_for_step(int step_index) {
#if AVABM_FAST_PHYSICS_MODE
return avabm_interval_runs_for_step(step_index, AVABM_SPAWN_OVERLAP_INTERVAL);
#else
(void)step_index; return true;
#endif
} static inline bool avabm_contact_runs_for_step(int step_index) {
#if AVABM_FAST_PHYSICS_MODE
return avabm_interval_runs_for_step(step_index, AVABM_CONTACT_INTERVAL);
#else
(void)step_index; return true;
#endif
} static inline bool avabm_reuse_persistent_grid_for_perception(bool initial_grid_valid, int step_index) {
#if AVABM_ECS_PERSISTENT_PERCEPTION_GRID_REUSE && AVABM_FAST_PHYSICS_MODE && AVABM_SPAWN_GRID_INSERT_FASTPATH
return initial_grid_valid && !avabm_spawn_overlap_runs_for_step(step_index) && !avabm_route_repair_runs_for_step(step_index);
#else
(void)initial_grid_valid; (void)step_index; return false;
#endif
} static inline int avabm_grid_rebuilds_for_step(bool initial_grid_valid, int step_index) { int rebuilds = 0; if (!initial_grid_valid) rebuilds += 1; if (avabm_spawn_overlap_runs_for_step(step_index)) rebuilds += 1; if (!avabm_reuse_persistent_grid_for_perception(initial_grid_valid, step_index)) { rebuilds += 1; }
if (avabm_route_repair_runs_for_step(step_index)) rebuilds += 1; rebuilds += 2; if (avabm_contact_runs_for_step(step_index)) rebuilds += CONTACT_RESOLVE_PASSES; return rebuilds; } static inline void avabm_reset_persistent_grid_epoch(StepTempBufferCache& cache, int64_t world_cells, cudaStream_t stream) {
if (cache.grid_cell_epoch.defined() && world_cells > 0) { cudaMemsetAsync(cache.grid_cell_epoch.data_ptr<int>(),0,static_cast<size_t>(world_cells) * sizeof(int),stream); } cache.grid_epoch = 1; cache.persistent_grid_valid = false; }
static void step_cuda_impl(torch::Tensor s,torch::Tensor x,torch::Tensor y,torch::Tensor speed,torch::Tensor accel,torch::Tensor heading,torch::Tensor steer_angle,torch::Tensor vehicle_length,torch::Tensor vehicle_width,torch::Tensor reaction_time,torch::Tensor min_gap,torch::Tensor lane_id,torch::Tensor active,torch::Tensor driver_type,torch::Tensor route_id,torch::Tensor route_pos,torch::Tensor vehicle_state,torch::Tensor connector_from_lane,torch::Tensor connector_to_lane,torch::Tensor connector_s,torch::Tensor connector_length,torch::Tensor lane_change_active,torch::Tensor lane_change_from_lane,torch::Tensor lane_change_to_lane,torch::Tensor lane_change_t,torch::Tensor lane_change_duration,torch::Tensor aggressiveness,torch::Tensor politeness,torch::Tensor risk_tolerance,torch::Tensor comfort_decel,torch::Tensor desired_speed_factor,torch::Tensor lc_cooldown,torch::Tensor turn_signal,torch::Tensor turn_signal_time,torch::Tensor lane_length,torch::Tensor lane_start_x,torch::Tensor lane_start_y,torch::Tensor lane_end_x,torch::Tensor lane_end_y,torch::Tensor lane_speed_limit,torch::Tensor lane_start_node,torch::Tensor lane_end_node,torch::Tensor left_lane,torch::Tensor right_lane,torch::Tensor conflict_lanes,torch::Tensor route_offsets,torch::Tensor route_lanes,torch::Tensor route_turns,torch::Tensor spawn_accumulator,torch::Tensor demand_vps,torch::Tensor demand_profile_vps,torch::Tensor demand_profile_has,int64_t demand_profile_slots,double demand_profile_slot_seconds,torch::Tensor spawn_lane,torch::Tensor spawn_route,torch::Tensor entry_time,torch::Tensor lane_cell_head,torch::Tensor lane_cell_next,torch::Tensor world_cell_head,torch::Tensor world_cell_next,double world_min_x,double world_min_y,double world_cell_size,int64_t world_grid_w,int64_t world_grid_h,torch::Tensor signal_node,torch::Tensor signal_turn,torch::Tensor signal_cycle,torch::Tensor signal_green_start,torch::Tensor signal_green_end,torch::Tensor signal_yellow_start,torch::Tensor signal_yellow_end,torch::Tensor rng_state,torch::Tensor metrics,double current_time,double dt,double av_penetration,int64_t max_agents,int64_t num_spawn_points,int64_t num_lanes,int64_t num_signals,int64_t step_index,torch::Tensor intersection_lock,torch::Tensor reservation_table,int64_t num_nodes,int64_t batch_steps) {
TORCH_CHECK(batch_steps > 0, "batch_steps must be positive"); TORCH_CHECK(batch_steps <= static_cast<int64_t>(std::numeric_limits<int>::max()), "batch_steps exceeds int range"); TORCH_CHECK(max_agents > 0, "max_agents must be positive"); TORCH_CHECK(num_lanes > 0, "num_lanes must be positive");
TORCH_CHECK(num_spawn_points >= 0, "num_spawn_points must be non-negative"); TORCH_CHECK(demand_profile_slots > 0, "demand_profile_slots must be positive"); TORCH_CHECK(num_signals >= 0, "num_signals must be non-negative"); TORCH_CHECK(num_nodes > 0, "num_nodes must be positive"); TORCH_CHECK(world_grid_w > 0, "world_grid_w must be positive");
TORCH_CHECK(world_grid_h > 0, "world_grid_h must be positive"); TORCH_CHECK(world_cell_size > 0.0, "world_cell_size must be positive"); TORCH_CHECK(std::isfinite(world_min_x), "world_min_x must be finite"); TORCH_CHECK(std::isfinite(world_min_y), "world_min_y must be finite"); TORCH_CHECK(std::isfinite(world_cell_size), "world_cell_size must be finite");
TORCH_CHECK(dt > 0.0, "dt must be positive"); TORCH_CHECK(dt <= 0.5, "dt must be <= 0.5"); TORCH_CHECK(std::isfinite(current_time), "current_time must be finite"); TORCH_CHECK(std::isfinite(dt), "dt must be finite"); TORCH_CHECK(std::isfinite(av_penetration), "av_penetration must be finite");
TORCH_CHECK(std::isfinite(demand_profile_slot_seconds), "demand_profile_slot_seconds must be finite"); const double final_batch_time = current_time + static_cast<double>(batch_steps - 1) * dt; TORCH_CHECK(std::isfinite(final_batch_time), "current_time + (batch_steps - 1) * dt must be finite");
TORCH_CHECK(demand_profile_slot_seconds > 0.0, "demand_profile_slot_seconds must be positive"); TORCH_CHECK(av_penetration >= 0.0 && av_penetration <= 1.0, "av_penetration must be in [0, 1]"); check_nonnegative_int64_to_int_range(max_agents, "max_agents"); check_nonnegative_int64_to_int_range(num_lanes, "num_lanes");
check_nonnegative_int64_to_int_range(num_spawn_points, "num_spawn_points"); check_nonnegative_int64_to_int_range(demand_profile_slots, "demand_profile_slots"); check_nonnegative_int64_to_int_range(num_signals, "num_signals"); check_nonnegative_int64_to_int_range(num_nodes, "num_nodes"); check_nonnegative_int64_to_int_range(world_grid_w, "world_grid_w");
check_nonnegative_int64_to_int_range(world_grid_h, "world_grid_h"); check_nonnegative_int64_to_int_range(step_index, "step_index"); TORCH_CHECK(step_index <= static_cast<int64_t>(std::numeric_limits<int>::max()) - (batch_steps - 1),"step_index + batch_steps - 1 exceeds int range");
TORCH_CHECK(world_grid_w <= std::numeric_limits<int64_t>::max() / world_grid_h,"world_grid_w * world_grid_h overflows int64"); const int64_t world_cells = world_grid_w * world_grid_h; TORCH_CHECK(world_cells <= static_cast<int64_t>(std::numeric_limits<int>::max()),"world_grid_w * world_grid_h exceeds int range");
TORCH_CHECK(num_nodes <= std::numeric_limits<int64_t>::max() / RES_HORIZON_SLOTS_BINDING,"num_nodes * RES_HORIZON_SLOTS overflows int64"); const int64_t reservation_slots = num_nodes * static_cast<int64_t>(RES_HORIZON_SLOTS_BINDING); CHECK_CUDA(s); const c10::cuda::CUDAGuard device_guard(s.device()); check_agent_float_tensor(s, "s", max_agents, s);
check_agent_float_tensor(x, "x", max_agents, s); check_agent_float_tensor(y, "y", max_agents, s); check_agent_float_tensor(speed, "speed", max_agents, s); check_agent_float_tensor(accel, "accel", max_agents, s); check_agent_float_tensor(heading, "heading", max_agents, s); check_agent_float_tensor(steer_angle, "steer_angle", max_agents, s);
check_agent_float_tensor(vehicle_length, "vehicle_length", max_agents, s); check_agent_float_tensor(vehicle_width, "vehicle_width", max_agents, s); check_agent_float_tensor(reaction_time, "reaction_time", max_agents, s); check_agent_float_tensor(min_gap, "min_gap", max_agents, s); check_agent_int_tensor(lane_id, "lane_id", max_agents, s);
check_agent_int_tensor(active, "active", max_agents, s); check_agent_int_tensor(driver_type, "driver_type", max_agents, s); check_agent_int_tensor(route_id, "route_id", max_agents, s); check_agent_int_tensor(route_pos, "route_pos", max_agents, s); check_agent_int_tensor(vehicle_state, "vehicle_state", max_agents, s);
check_agent_int_tensor(connector_from_lane, "connector_from_lane", max_agents, s); check_agent_int_tensor(connector_to_lane, "connector_to_lane", max_agents, s); check_agent_float_tensor(connector_s, "connector_s", max_agents, s); check_agent_float_tensor(connector_length, "connector_length", max_agents, s);
check_agent_int_tensor(lane_change_active, "lane_change_active", max_agents, s); check_agent_int_tensor(lane_change_from_lane, "lane_change_from_lane", max_agents, s); check_agent_int_tensor(lane_change_to_lane, "lane_change_to_lane", max_agents, s); check_agent_float_tensor(lane_change_t, "lane_change_t", max_agents, s);
check_agent_float_tensor(lane_change_duration, "lane_change_duration", max_agents, s); check_agent_float_tensor(aggressiveness, "aggressiveness", max_agents, s); check_agent_float_tensor(politeness, "politeness", max_agents, s); check_agent_float_tensor(risk_tolerance, "risk_tolerance", max_agents, s);
check_agent_float_tensor(comfort_decel, "comfort_decel", max_agents, s); check_agent_float_tensor(desired_speed_factor, "desired_speed_factor", max_agents, s); check_agent_float_tensor(lc_cooldown, "lc_cooldown", max_agents, s); check_agent_int_tensor(turn_signal, "turn_signal", max_agents, s);
check_agent_float_tensor(turn_signal_time, "turn_signal_time", max_agents, s); check_agent_float_tensor(entry_time, "entry_time", max_agents, s); check_lane_float_tensor(lane_length, "lane_length", num_lanes, s); check_lane_float_tensor(lane_start_x, "lane_start_x", num_lanes, s); check_lane_float_tensor(lane_start_y, "lane_start_y", num_lanes, s);
check_lane_float_tensor(lane_end_x, "lane_end_x", num_lanes, s); check_lane_float_tensor(lane_end_y, "lane_end_y", num_lanes, s); check_lane_float_tensor(lane_speed_limit, "lane_speed_limit", num_lanes, s); check_lane_int_tensor(lane_start_node, "lane_start_node", num_lanes, s); check_lane_int_tensor(lane_end_node, "lane_end_node", num_lanes, s);
check_lane_int_tensor(left_lane, "left_lane", num_lanes, s); check_lane_int_tensor(right_lane, "right_lane", num_lanes, s); CHECK_INPUT(conflict_lanes); CHECK_INT32(conflict_lanes); check_same_cuda_device(conflict_lanes, "conflict_lanes", s, "s"); TORCH_CHECK(conflict_lanes.dim() == 2, "conflict_lanes must be 2D");
TORCH_CHECK(conflict_lanes.size(0) == num_lanes, "conflict_lanes.size(0) must equal num_lanes"); TORCH_CHECK(conflict_lanes.size(1) == MAX_CONFLICT_LANES_BINDING,"conflict_lanes.size(1) must equal ",MAX_CONFLICT_LANES_BINDING); CHECK_INPUT(route_offsets); CHECK_INT32(route_offsets); check_same_cuda_device(route_offsets, "route_offsets", s, "s");
TORCH_CHECK(route_offsets.dim() == 1, "route_offsets must be 1D"); TORCH_CHECK(route_offsets.numel() >= 2, "route_offsets must have at least 2 elements"); TORCH_CHECK(route_offsets.numel() <= static_cast<int64_t>(std::numeric_limits<int>::max()),"route_offsets.numel() exceeds int range"); int64_t num_routes = route_offsets.numel() - 1;
check_nonnegative_int64_to_int_range(num_routes, "num_routes"); CHECK_INPUT(route_lanes); CHECK_INT32(route_lanes); check_same_cuda_device(route_lanes, "route_lanes", s, "s"); TORCH_CHECK(route_lanes.dim() == 1, "route_lanes must be 1D");
TORCH_CHECK(route_lanes.numel() <= static_cast<int64_t>(std::numeric_limits<int>::max()),"route_lanes.numel() exceeds int range"); CHECK_INPUT(route_turns); CHECK_INT32(route_turns); check_same_cuda_device(route_turns, "route_turns", s, "s"); TORCH_CHECK(route_turns.dim() == 1, "route_turns must be 1D");
TORCH_CHECK(route_turns.numel() == route_lanes.numel(), "route_turns.numel() must equal route_lanes.numel()"); check_spawn_float_tensor(spawn_accumulator, "spawn_accumulator", num_spawn_points, s); check_spawn_float_tensor(demand_vps, "demand_vps", num_spawn_points, s); CHECK_INPUT(demand_profile_vps); CHECK_FLOAT32(demand_profile_vps);
check_same_cuda_device(demand_profile_vps, "demand_profile_vps", s, "s"); TORCH_CHECK(demand_profile_vps.dim() == 2, "demand_profile_vps must be 2D"); TORCH_CHECK(demand_profile_vps.size(0) == num_spawn_points, "demand_profile_vps.size(0) must equal num_spawn_points");
TORCH_CHECK(demand_profile_vps.size(1) == demand_profile_slots, "demand_profile_vps.size(1) must equal demand_profile_slots"); check_spawn_int_tensor(demand_profile_has, "demand_profile_has", num_spawn_points, s); check_spawn_int_tensor(spawn_lane, "spawn_lane", num_spawn_points, s); check_spawn_int_tensor(spawn_route, "spawn_route", num_spawn_points, s);
CHECK_INPUT(lane_cell_head); CHECK_INT32(lane_cell_head); check_same_cuda_device(lane_cell_head, "lane_cell_head", s, "s"); TORCH_CHECK(lane_cell_head.dim() == 1, "lane_cell_head must be 1D"); TORCH_CHECK(lane_cell_head.numel() >= num_lanes, "lane_cell_head must have at least num_lanes elements");
TORCH_CHECK(lane_cell_head.numel() % num_lanes == 0, "lane_cell_head.numel() must be a multiple of num_lanes"); CHECK_INPUT(lane_cell_next); CHECK_INT32(lane_cell_next); check_same_cuda_device(lane_cell_next, "lane_cell_next", s, "s"); TORCH_CHECK(lane_cell_next.dim() == 1, "lane_cell_next must be 1D");
TORCH_CHECK(lane_cell_next.numel() == max_agents || lane_cell_next.numel() == 0,"lane_cell_next.numel() must equal max_agents or be empty"); CHECK_INPUT(world_cell_head); CHECK_INT32(world_cell_head); check_same_cuda_device(world_cell_head, "world_cell_head", s, "s"); TORCH_CHECK(world_cell_head.dim() == 1, "world_cell_head must be 1D");
TORCH_CHECK(world_cell_head.numel() == world_cells, "world_cell_head.numel() must equal world_grid_w * world_grid_h"); CHECK_INPUT(world_cell_next); CHECK_INT32(world_cell_next); check_same_cuda_device(world_cell_next, "world_cell_next", s, "s"); TORCH_CHECK(world_cell_next.dim() == 1, "world_cell_next must be 1D");
TORCH_CHECK(world_cell_next.numel() == max_agents, "world_cell_next.numel() must equal max_agents"); check_signal_int_tensor(signal_node, "signal_node", num_signals, s); check_signal_int_tensor(signal_turn, "signal_turn", num_signals, s); check_signal_float_tensor(signal_cycle, "signal_cycle", num_signals, s);
check_signal_float_tensor(signal_green_start, "signal_green_start", num_signals, s); check_signal_float_tensor(signal_green_end, "signal_green_end", num_signals, s); check_signal_float_tensor(signal_yellow_start, "signal_yellow_start", num_signals, s); check_signal_float_tensor(signal_yellow_end, "signal_yellow_end", num_signals, s); CHECK_INPUT(rng_state);
CHECK_INT32(rng_state); check_same_cuda_device(rng_state, "rng_state", s, "s"); TORCH_CHECK(rng_state.dim() == 1, "rng_state must be 1D"); TORCH_CHECK(rng_state.numel() >= max_agents + num_spawn_points,"rng_state.numel() must be at least max_agents + num_spawn_points"); CHECK_INPUT(metrics); CHECK_FLOAT32(metrics);
check_same_cuda_device(metrics, "metrics", s, "s"); TORCH_CHECK(metrics.dim() == 1, "metrics must be 1D"); TORCH_CHECK(metrics.numel() >= METRICS_SIZE_MIN, "metrics must have at least ", METRICS_SIZE_MIN, " elements"); check_node_int_tensor(intersection_lock, "intersection_lock", num_nodes, s);
check_1d_tensor(reservation_table,"reservation_table",reservation_slots,torch::kInt32,s); g_step_temp_buffers.ensure(max_agents, world_cells, s); PerceptionSoA perception{}; perception.front_gap = g_step_temp_buffers.perception_front_gap.data_ptr<float>(); perception.front_speed = g_step_temp_buffers.perception_front_speed.data_ptr<float>();
perception.front_s = g_step_temp_buffers.perception_front_s.data_ptr<float>(); perception.front_length = g_step_temp_buffers.perception_front_length.data_ptr<float>(); perception.front_lane = g_step_temp_buffers.perception_front_lane.data_ptr<int>(); perception.target_front_gap = g_step_temp_buffers.perception_target_front_gap.data_ptr<float>();
perception.target_front_speed = g_step_temp_buffers.perception_target_front_speed.data_ptr<float>(); perception.target_rear_gap = g_step_temp_buffers.perception_target_rear_gap.data_ptr<float>(); perception.target_rear_speed = g_step_temp_buffers.perception_target_rear_speed.data_ptr<float>(); DecisionSoA decision{};
decision.desired_speed = g_step_temp_buffers.decision_desired_speed.data_ptr<float>(); decision.target_accel = g_step_temp_buffers.decision_target_accel.data_ptr<float>(); decision.wants_lane_change = g_step_temp_buffers.decision_wants_lane_change.data_ptr<int>(); decision.lane_change_target = g_step_temp_buffers.decision_lane_change_target.data_ptr<int>();
decision.wants_connector = g_step_temp_buffers.decision_wants_connector.data_ptr<int>(); decision.connector_target_lane = g_step_temp_buffers.decision_connector_target_lane.data_ptr<int>(); decision.should_exit = g_step_temp_buffers.decision_should_exit.data_ptr<int>();
ECSArrays ecs = make_ecs_arrays(s,x,y,speed,accel,heading,steer_angle,vehicle_length,vehicle_width,reaction_time,min_gap,lane_id,active,driver_type,route_id,route_pos,vehicle_state,connector_from_lane,connector_to_lane,connector_s,connector_length,lane_change_active,lane_change_from_lane,lane_change_to_lane,lane_change_t,lane_change_duration,aggressiveness,politeness,risk_tolerance,comfort_decel,desired_speed_factor,lc_cooldown,turn_signal,turn_signal_time,entry_time);
RoadNetwork road{}; road.lane_length = lane_length.data_ptr<float>(); road.lane_start_x = lane_start_x.data_ptr<float>(); road.lane_start_y = lane_start_y.data_ptr<float>(); road.lane_end_x = lane_end_x.data_ptr<float>(); road.lane_end_y = lane_end_y.data_ptr<float>(); road.lane_speed_limit = lane_speed_limit.data_ptr<float>();
road.lane_start_node = lane_start_node.data_ptr<int>(); road.lane_end_node = lane_end_node.data_ptr<int>(); road.left_lane = left_lane.data_ptr<int>(); road.right_lane = right_lane.data_ptr<int>(); road.route_offsets = route_offsets.data_ptr<int>(); road.route_lanes = route_lanes.data_ptr<int>(); road.route_turns = route_turns.data_ptr<int>();
road.num_lanes = static_cast<int>(num_lanes); road.num_nodes = static_cast<int>(num_nodes); road.num_routes = static_cast<int>(num_routes); Signals signals{}; signals.signal_node = signal_node.data_ptr<int>(); signals.signal_turn = signal_turn.data_ptr<int>(); signals.signal_cycle = signal_cycle.data_ptr<float>();
signals.signal_green_start = signal_green_start.data_ptr<float>(); signals.signal_green_end = signal_green_end.data_ptr<float>(); signals.signal_yellow_start = signal_yellow_start.data_ptr<float>(); signals.signal_yellow_end = signal_yellow_end.data_ptr<float>(); signals.num_signals = static_cast<int>(num_signals); SpatialGrid grid_template{};
grid_template.cell_head = world_cell_head.data_ptr<int>(); grid_template.cell_next = world_cell_next.data_ptr<int>(); grid_template.cell_epoch = g_step_temp_buffers.grid_cell_epoch.data_ptr<int>(); grid_template.epoch = 1; grid_template.lane_cell_head = lane_cell_head.numel() > 0 ? lane_cell_head.data_ptr<int>() : nullptr;
grid_template.lane_cell_next = lane_cell_next.numel() > 0 ? lane_cell_next.data_ptr<int>() : nullptr; grid_template.lane_cells_per_lane = static_cast<int>(lane_cell_head.numel() / num_lanes); grid_template.min_x = static_cast<float>(world_min_x); grid_template.min_y = static_cast<float>(world_min_y);
grid_template.cell_size = static_cast<float>(world_cell_size); grid_template.width = static_cast<int>(world_grid_w); grid_template.height = static_cast<int>(world_grid_h); SpawnConfig spawn{}; spawn.spawn_accumulator = spawn_accumulator.data_ptr<float>(); spawn.demand_vps = demand_vps.data_ptr<float>();
spawn.demand_profile_vps = demand_profile_vps.data_ptr<float>(); spawn.demand_profile_has = demand_profile_has.data_ptr<int>(); spawn.spawn_lane = spawn_lane.data_ptr<int>(); spawn.spawn_route = spawn_route.data_ptr<int>(); spawn.spawn_alloc_cursor = g_step_temp_buffers.spawn_alloc_cursor.data_ptr<int>();
spawn.num_spawn_points = static_cast<int>(num_spawn_points); spawn.demand_profile_slots = static_cast<int>(demand_profile_slots); spawn.demand_profile_slot_seconds = static_cast<float>(demand_profile_slot_seconds); spawn.av_penetration = static_cast<float>(av_penetration); auto stream = at::cuda::getCurrentCUDAStream(s.device().index());
if (step_index <= 0) { g_step_temp_buffers.persistent_grid_valid = false; } { pybind11::gil_scoped_release no_gil; for (int64_t batch_i = 0; batch_i < batch_steps; ++batch_i) { SpatialGrid grid = grid_template; const int substep_index = static_cast<int>(step_index + batch_i); if (g_step_temp_buffers.grid_epoch > std::numeric_limits<int>::max() - 64) {
avabm_reset_persistent_grid_epoch(g_step_temp_buffers, world_cells, stream.stream()); }
#if AVABM_PERSISTENT_START_GRID
const bool initial_grid_valid = g_step_temp_buffers.persistent_grid_valid;
#else
const bool initial_grid_valid = false; g_step_temp_buffers.persistent_grid_valid = false;
#endif
grid.epoch = g_step_temp_buffers.grid_epoch;
launch_step_cuda_ecs(ecs,road,signals,grid,spawn,perception,decision,reservation_table.data_ptr<int>(),reinterpret_cast<uint32_t*>(rng_state.data_ptr<int>()),metrics.data_ptr<float>(),g_step_temp_buffers.active_ids.data_ptr<int>(),g_step_temp_buffers.active_count.data_ptr<int>(),g_step_temp_buffers.lane_active_ids.data_ptr<int>(),g_step_temp_buffers.lane_active_count.data_ptr<int>(),g_step_temp_buffers.connector_active_ids.data_ptr<int>(),g_step_temp_buffers.connector_active_count.data_ptr<int>(),initial_grid_valid ? 1 : 0,static_cast<float>(current_time + static_cast<double>(batch_i) * dt),static_cast<float>(dt),static_cast<int>(max_agents),substep_index,stream.stream());
g_step_temp_buffers.grid_epoch += avabm_grid_rebuilds_for_step(initial_grid_valid, substep_index); g_step_temp_buffers.persistent_grid_valid = true; } } C10_CUDA_KERNEL_LAUNCH_CHECK(); }
void step_cuda(torch::Tensor s,torch::Tensor x,torch::Tensor y,torch::Tensor speed,torch::Tensor accel,torch::Tensor heading,torch::Tensor steer_angle,torch::Tensor vehicle_length,torch::Tensor vehicle_width,torch::Tensor reaction_time,torch::Tensor min_gap,torch::Tensor lane_id,torch::Tensor active,torch::Tensor driver_type,torch::Tensor route_id,torch::Tensor route_pos,torch::Tensor vehicle_state,torch::Tensor connector_from_lane,torch::Tensor connector_to_lane,torch::Tensor connector_s,torch::Tensor connector_length,torch::Tensor lane_change_active,torch::Tensor lane_change_from_lane,torch::Tensor lane_change_to_lane,torch::Tensor lane_change_t,torch::Tensor lane_change_duration,torch::Tensor aggressiveness,torch::Tensor politeness,torch::Tensor risk_tolerance,torch::Tensor comfort_decel,torch::Tensor desired_speed_factor,torch::Tensor lc_cooldown,torch::Tensor turn_signal,torch::Tensor turn_signal_time,torch::Tensor lane_length,torch::Tensor lane_start_x,torch::Tensor lane_start_y,torch::Tensor lane_end_x,torch::Tensor lane_end_y,torch::Tensor lane_speed_limit,torch::Tensor lane_start_node,torch::Tensor lane_end_node,torch::Tensor left_lane,torch::Tensor right_lane,torch::Tensor conflict_lanes,torch::Tensor route_offsets,torch::Tensor route_lanes,torch::Tensor route_turns,torch::Tensor spawn_accumulator,torch::Tensor demand_vps,torch::Tensor demand_profile_vps,torch::Tensor demand_profile_has,int64_t demand_profile_slots,double demand_profile_slot_seconds,torch::Tensor spawn_lane,torch::Tensor spawn_route,torch::Tensor entry_time,torch::Tensor lane_cell_head,torch::Tensor lane_cell_next,torch::Tensor world_cell_head,torch::Tensor world_cell_next,double world_min_x,double world_min_y,double world_cell_size,int64_t world_grid_w,int64_t world_grid_h,torch::Tensor signal_node,torch::Tensor signal_turn,torch::Tensor signal_cycle,torch::Tensor signal_green_start,torch::Tensor signal_green_end,torch::Tensor signal_yellow_start,torch::Tensor signal_yellow_end,torch::Tensor rng_state,torch::Tensor metrics,double current_time,double dt,double av_penetration,int64_t max_agents,int64_t num_spawn_points,int64_t num_lanes,int64_t num_signals,int64_t step_index,torch::Tensor intersection_lock,torch::Tensor reservation_table,int64_t num_nodes) {
step_cuda_impl(s,x,y,speed,accel,heading,steer_angle,vehicle_length,vehicle_width,reaction_time,min_gap,lane_id,active,driver_type,route_id,route_pos,vehicle_state,connector_from_lane,connector_to_lane,connector_s,connector_length,lane_change_active,lane_change_from_lane,lane_change_to_lane,lane_change_t,lane_change_duration,aggressiveness,politeness,risk_tolerance,comfort_decel,desired_speed_factor,lc_cooldown,turn_signal,turn_signal_time,lane_length,lane_start_x,lane_start_y,lane_end_x,lane_end_y,lane_speed_limit,lane_start_node,lane_end_node,left_lane,right_lane,conflict_lanes,route_offsets,route_lanes,route_turns,spawn_accumulator,demand_vps,demand_profile_vps,demand_profile_has,demand_profile_slots,demand_profile_slot_seconds,spawn_lane,spawn_route,entry_time,lane_cell_head,lane_cell_next,world_cell_head,world_cell_next,world_min_x,world_min_y,world_cell_size,world_grid_w,world_grid_h,signal_node,signal_turn,signal_cycle,signal_green_start,signal_green_end,signal_yellow_start,signal_yellow_end,rng_state,metrics,current_time,dt,av_penetration,max_agents,num_spawn_points,num_lanes,num_signals,step_index,intersection_lock,reservation_table,num_nodes,1);
}
void step_batch_cuda(torch::Tensor s,torch::Tensor x,torch::Tensor y,torch::Tensor speed,torch::Tensor accel,torch::Tensor heading,torch::Tensor steer_angle,torch::Tensor vehicle_length,torch::Tensor vehicle_width,torch::Tensor reaction_time,torch::Tensor min_gap,torch::Tensor lane_id,torch::Tensor active,torch::Tensor driver_type,torch::Tensor route_id,torch::Tensor route_pos,torch::Tensor vehicle_state,torch::Tensor connector_from_lane,torch::Tensor connector_to_lane,torch::Tensor connector_s,torch::Tensor connector_length,torch::Tensor lane_change_active,torch::Tensor lane_change_from_lane,torch::Tensor lane_change_to_lane,torch::Tensor lane_change_t,torch::Tensor lane_change_duration,torch::Tensor aggressiveness,torch::Tensor politeness,torch::Tensor risk_tolerance,torch::Tensor comfort_decel,torch::Tensor desired_speed_factor,torch::Tensor lc_cooldown,torch::Tensor turn_signal,torch::Tensor turn_signal_time,torch::Tensor lane_length,torch::Tensor lane_start_x,torch::Tensor lane_start_y,torch::Tensor lane_end_x,torch::Tensor lane_end_y,torch::Tensor lane_speed_limit,torch::Tensor lane_start_node,torch::Tensor lane_end_node,torch::Tensor left_lane,torch::Tensor right_lane,torch::Tensor conflict_lanes,torch::Tensor route_offsets,torch::Tensor route_lanes,torch::Tensor route_turns,torch::Tensor spawn_accumulator,torch::Tensor demand_vps,torch::Tensor demand_profile_vps,torch::Tensor demand_profile_has,int64_t demand_profile_slots,double demand_profile_slot_seconds,torch::Tensor spawn_lane,torch::Tensor spawn_route,torch::Tensor entry_time,torch::Tensor lane_cell_head,torch::Tensor lane_cell_next,torch::Tensor world_cell_head,torch::Tensor world_cell_next,double world_min_x,double world_min_y,double world_cell_size,int64_t world_grid_w,int64_t world_grid_h,torch::Tensor signal_node,torch::Tensor signal_turn,torch::Tensor signal_cycle,torch::Tensor signal_green_start,torch::Tensor signal_green_end,torch::Tensor signal_yellow_start,torch::Tensor signal_yellow_end,torch::Tensor rng_state,torch::Tensor metrics,double current_time,double dt,double av_penetration,int64_t max_agents,int64_t num_spawn_points,int64_t num_lanes,int64_t num_signals,int64_t step_index,torch::Tensor intersection_lock,torch::Tensor reservation_table,int64_t num_nodes,int64_t batch_steps) {
step_cuda_impl(s,x,y,speed,accel,heading,steer_angle,vehicle_length,vehicle_width,reaction_time,min_gap,lane_id,active,driver_type,route_id,route_pos,vehicle_state,connector_from_lane,connector_to_lane,connector_s,connector_length,lane_change_active,lane_change_from_lane,lane_change_to_lane,lane_change_t,lane_change_duration,aggressiveness,politeness,risk_tolerance,comfort_decel,desired_speed_factor,lc_cooldown,turn_signal,turn_signal_time,lane_length,lane_start_x,lane_start_y,lane_end_x,lane_end_y,lane_speed_limit,lane_start_node,lane_end_node,left_lane,right_lane,conflict_lanes,route_offsets,route_lanes,route_turns,spawn_accumulator,demand_vps,demand_profile_vps,demand_profile_has,demand_profile_slots,demand_profile_slot_seconds,spawn_lane,spawn_route,entry_time,lane_cell_head,lane_cell_next,world_cell_head,world_cell_next,world_min_x,world_min_y,world_cell_size,world_grid_w,world_grid_h,signal_node,signal_turn,signal_cycle,signal_green_start,signal_green_end,signal_yellow_start,signal_yellow_end,rng_state,metrics,current_time,dt,av_penetration,max_agents,num_spawn_points,num_lanes,num_signals,step_index,intersection_lock,reservation_table,num_nodes,batch_steps);
} void register_render_vbo(int64_t vbo) { TORCH_CHECK(vbo >= 0, "vbo must be non-negative"); TORCH_CHECK(vbo <= static_cast<int64_t>(std::numeric_limits<unsigned int>::max()),"vbo exceeds unsigned int range"); register_render_vbo_cuda(static_cast<unsigned int>(vbo)); C10_CUDA_KERNEL_LAUNCH_CHECK(); } void set_vehicle_texture_render(bool enabled) {
set_vehicle_texture_render_cuda(enabled ? 1 : 0); C10_CUDA_KERNEL_LAUNCH_CHECK(); } int64_t update_render_vbo(torch::Tensor x,torch::Tensor y,torch::Tensor heading,torch::Tensor steer_angle,torch::Tensor active,torch::Tensor driver_type,torch::Tensor vehicle_length,torch::Tensor vehicle_width,int64_t max_agents) {
TORCH_CHECK(max_agents > 0, "max_agents must be positive"); check_nonnegative_int64_to_int_range(max_agents, "max_agents"); CHECK_CUDA(x); const c10::cuda::CUDAGuard device_guard(x.device()); check_agent_float_tensor(x, "x", max_agents, x); check_agent_float_tensor(y, "y", max_agents, x); check_agent_float_tensor(heading, "heading", max_agents, x);
check_agent_float_tensor(steer_angle, "steer_angle", max_agents, x); check_agent_int_tensor(active, "active", max_agents, x); check_agent_int_tensor(driver_type, "driver_type", max_agents, x); check_agent_float_tensor(vehicle_length, "vehicle_length", max_agents, x); check_agent_float_tensor(vehicle_width, "vehicle_width", max_agents, x); ECSArrays ecs{};
ecs.alive = active.data_ptr<int>(); ecs.x = x.data_ptr<float>(); ecs.y = y.data_ptr<float>(); ecs.heading = heading.data_ptr<float>(); ecs.steer_angle = steer_angle.data_ptr<float>(); ecs.driver_type = driver_type.data_ptr<int>(); ecs.length = vehicle_length.data_ptr<float>(); ecs.width = vehicle_width.data_ptr<float>();
auto int_opts = x.options().dtype(torch::kInt32); if (!g_step_temp_buffers.render_count.defined() || !g_step_temp_buffers.render_count.is_cuda() || g_step_temp_buffers.render_count.device() != x.device()) { g_step_temp_buffers.render_count = torch::empty({1}, int_opts); }
if (!g_step_temp_buffers.render_previous_count.defined() || !g_step_temp_buffers.render_previous_count.is_cuda() || g_step_temp_buffers.render_previous_count.device() != x.device()) { g_step_temp_buffers.render_previous_count = torch::full({1}, static_cast<int>(max_agents), int_opts); } const int* active_ids_ptr = nullptr;
const int* active_count_ptr = nullptr;
if (g_step_temp_buffers.active_ids.defined() && g_step_temp_buffers.active_count.defined() && g_step_temp_buffers.active_ids.is_cuda() && g_step_temp_buffers.active_count.is_cuda() && g_step_temp_buffers.active_ids.device() == x.device() && g_step_temp_buffers.active_count.device() == x.device() && g_step_temp_buffers.active_ids.numel() == max_agents) {
active_ids_ptr = g_step_temp_buffers.active_ids.data_ptr<int>(); active_count_ptr = g_step_temp_buffers.active_count.data_ptr<int>(); } auto stream = at::cuda::getCurrentCUDAStream(x.device().index());
launch_render_vbo_cuda_ecs(ecs,static_cast<int>(max_agents),active_ids_ptr,active_count_ptr,g_step_temp_buffers.render_count.data_ptr<int>(),g_step_temp_buffers.render_previous_count.data_ptr<int>(),stream.stream(),0); C10_CUDA_KERNEL_LAUNCH_CHECK(); int host_count = 0;
cudaMemcpyAsync(&host_count,g_step_temp_buffers.render_count.data_ptr<int>(),sizeof(int),cudaMemcpyDeviceToHost,stream.stream()); cudaStreamSynchronize(stream.stream()); C10_CUDA_KERNEL_LAUNCH_CHECK(); if (host_count < 0) host_count = 0; if (host_count > max_agents) host_count = static_cast<int>(max_agents); return static_cast<int64_t>(host_count); }
int64_t update_render_vbo_full_draw(torch::Tensor x,torch::Tensor y,torch::Tensor heading,torch::Tensor steer_angle,torch::Tensor active,torch::Tensor driver_type,torch::Tensor vehicle_length,torch::Tensor vehicle_width,int64_t max_agents) { TORCH_CHECK(max_agents > 0, "max_agents must be positive");
check_nonnegative_int64_to_int_range(max_agents, "max_agents"); CHECK_CUDA(x); const c10::cuda::CUDAGuard device_guard(x.device()); check_agent_float_tensor(x, "x", max_agents, x); check_agent_float_tensor(y, "y", max_agents, x); check_agent_float_tensor(heading, "heading", max_agents, x); check_agent_float_tensor(steer_angle, "steer_angle", max_agents, x);
check_agent_int_tensor(active, "active", max_agents, x); check_agent_int_tensor(driver_type, "driver_type", max_agents, x); check_agent_float_tensor(vehicle_length, "vehicle_length", max_agents, x); check_agent_float_tensor(vehicle_width, "vehicle_width", max_agents, x); ECSArrays ecs{}; ecs.alive = active.data_ptr<int>(); ecs.x = x.data_ptr<float>();
ecs.y = y.data_ptr<float>(); ecs.heading = heading.data_ptr<float>(); ecs.steer_angle = steer_angle.data_ptr<float>(); ecs.driver_type = driver_type.data_ptr<int>(); ecs.length = vehicle_length.data_ptr<float>(); ecs.width = vehicle_width.data_ptr<float>(); auto int_opts = x.options().dtype(torch::kInt32);
if (!g_step_temp_buffers.render_count.defined() || !g_step_temp_buffers.render_count.is_cuda() || g_step_temp_buffers.render_count.device() != x.device()) { g_step_temp_buffers.render_count = torch::empty({1}, int_opts); }
if (!g_step_temp_buffers.render_previous_count.defined() || !g_step_temp_buffers.render_previous_count.is_cuda() || g_step_temp_buffers.render_previous_count.device() != x.device()) { g_step_temp_buffers.render_previous_count = torch::full({1}, static_cast<int>(max_agents), int_opts); } const int* active_ids_ptr = nullptr;
const int* active_count_ptr = nullptr;
if (g_step_temp_buffers.active_ids.defined() && g_step_temp_buffers.active_count.defined() && g_step_temp_buffers.active_ids.is_cuda() && g_step_temp_buffers.active_count.is_cuda() && g_step_temp_buffers.active_ids.device() == x.device() && g_step_temp_buffers.active_count.device() == x.device() && g_step_temp_buffers.active_ids.numel() == max_agents) {
active_ids_ptr = g_step_temp_buffers.active_ids.data_ptr<int>(); active_count_ptr = g_step_temp_buffers.active_count.data_ptr<int>(); } auto stream = at::cuda::getCurrentCUDAStream(x.device().index());
launch_render_vbo_cuda_ecs(ecs,static_cast<int>(max_agents),active_ids_ptr,active_count_ptr,g_step_temp_buffers.render_count.data_ptr<int>(),g_step_temp_buffers.render_previous_count.data_ptr<int>(),stream.stream(),1); C10_CUDA_KERNEL_LAUNCH_CHECK(); return max_agents; }
int64_t update_render_vbo_interpolated_full_draw(torch::Tensor prev_x,torch::Tensor prev_y,torch::Tensor prev_heading,torch::Tensor prev_steer_angle,torch::Tensor prev_active,torch::Tensor x,torch::Tensor y,torch::Tensor heading,torch::Tensor steer_angle,torch::Tensor active,torch::Tensor driver_type,torch::Tensor vehicle_length,torch::Tensor vehicle_width,torch::Tensor turn_signal,torch::Tensor turn_signal_time,int64_t max_agents,double alpha) {
TORCH_CHECK(max_agents > 0, "max_agents must be positive"); check_nonnegative_int64_to_int_range(max_agents, "max_agents"); TORCH_CHECK(std::isfinite(alpha), "alpha must be finite"); CHECK_CUDA(x); const c10::cuda::CUDAGuard device_guard(x.device()); check_agent_float_tensor(prev_x, "prev_x", max_agents, x);
check_agent_float_tensor(prev_y, "prev_y", max_agents, x); check_agent_float_tensor(prev_heading, "prev_heading", max_agents, x); check_agent_float_tensor(prev_steer_angle, "prev_steer_angle", max_agents, x); check_agent_int_tensor(prev_active, "prev_active", max_agents, x); check_agent_float_tensor(x, "x", max_agents, x);
check_agent_float_tensor(y, "y", max_agents, x); check_agent_float_tensor(heading, "heading", max_agents, x); check_agent_float_tensor(steer_angle, "steer_angle", max_agents, x); check_agent_int_tensor(active, "active", max_agents, x); check_agent_int_tensor(driver_type, "driver_type", max_agents, x);
check_agent_float_tensor(vehicle_length, "vehicle_length", max_agents, x); check_agent_float_tensor(vehicle_width, "vehicle_width", max_agents, x); check_agent_int_tensor(turn_signal, "turn_signal", max_agents, x); check_agent_float_tensor(turn_signal_time, "turn_signal_time", max_agents, x); float a = static_cast<float>(alpha); if (a < 0.0f) a = 0.0f;
if (a > 1.0f) a = 1.0f; ECSArrays prev_ecs{}; prev_ecs.alive = prev_active.data_ptr<int>(); prev_ecs.x = prev_x.data_ptr<float>(); prev_ecs.y = prev_y.data_ptr<float>(); prev_ecs.heading = prev_heading.data_ptr<float>(); prev_ecs.steer_angle = prev_steer_angle.data_ptr<float>(); ECSArrays curr_ecs{}; curr_ecs.alive = active.data_ptr<int>();
curr_ecs.x = x.data_ptr<float>(); curr_ecs.y = y.data_ptr<float>(); curr_ecs.heading = heading.data_ptr<float>(); curr_ecs.steer_angle = steer_angle.data_ptr<float>(); curr_ecs.driver_type = driver_type.data_ptr<int>(); curr_ecs.length = vehicle_length.data_ptr<float>(); curr_ecs.width = vehicle_width.data_ptr<float>();
curr_ecs.turn_signal = turn_signal.data_ptr<int>(); curr_ecs.turn_signal_time = turn_signal_time.data_ptr<float>(); auto int_opts = x.options().dtype(torch::kInt32); if (!g_step_temp_buffers.render_count.defined() || !g_step_temp_buffers.render_count.is_cuda() || g_step_temp_buffers.render_count.device() != x.device()) {
g_step_temp_buffers.render_count = torch::empty({1}, int_opts); } if (!g_step_temp_buffers.render_previous_count.defined() || !g_step_temp_buffers.render_previous_count.is_cuda() || g_step_temp_buffers.render_previous_count.device() != x.device()) { g_step_temp_buffers.render_previous_count = torch::full({1}, static_cast<int>(max_agents), int_opts); }
const int* active_ids_ptr = nullptr; const int* active_count_ptr = nullptr;
if (g_step_temp_buffers.active_ids.defined() && g_step_temp_buffers.active_count.defined() && g_step_temp_buffers.active_ids.is_cuda() && g_step_temp_buffers.active_count.is_cuda() && g_step_temp_buffers.active_ids.device() == x.device() && g_step_temp_buffers.active_count.device() == x.device() && g_step_temp_buffers.active_ids.numel() == max_agents) {
active_ids_ptr = g_step_temp_buffers.active_ids.data_ptr<int>(); active_count_ptr = g_step_temp_buffers.active_count.data_ptr<int>(); } auto stream = at::cuda::getCurrentCUDAStream(x.device().index());
launch_render_vbo_interpolated_cuda_ecs(prev_ecs,curr_ecs,static_cast<int>(max_agents),active_ids_ptr,active_count_ptr,g_step_temp_buffers.render_count.data_ptr<int>(),g_step_temp_buffers.render_previous_count.data_ptr<int>(),stream.stream(),1,a); C10_CUDA_KERNEL_LAUNCH_CHECK(); return max_agents; } void unregister_render_vbo() {
unregister_render_vbo_cuda(); C10_CUDA_KERNEL_LAUNCH_CHECK(); } PYBIND11_MODULE(TORCH_EXTENSION_NAME, m) { m.def("step",&step_cuda,"CUDA ECS traffic ABM step with perception, decision, lane-change, connector, collision, safety, and metrics systems");
m.def("step_batch",&step_batch_cuda,"Batched CUDA ECS traffic ABM steps; launches the same per-tick pipeline sequentially on one stream after one validation pass"); m.def("register_render_vbo",&register_render_vbo,"Register OpenGL VBO for CUDA rendering");
m.def("set_vehicle_texture_render",&set_vehicle_texture_render,"Enable or disable textured vehicle rendering in the CUDA VBO writer"); m.def("update_render_vbo",&update_render_vbo,"Update OpenGL VBO from ECS CUDA tensors");
m.def("update_render_vbo_full_draw",&update_render_vbo_full_draw,"Update OpenGL VBO without GPU-to-CPU draw-count synchronization; unused dense slots are cleared on GPU");
m.def("update_render_vbo_interpolated_full_draw",&update_render_vbo_interpolated_full_draw,"Update OpenGL VBO from stable render snapshots with GPU-side interpolation and no draw-count readback"); m.def("unregister_render_vbo",&unregister_render_vbo,"Unregister OpenGL VBO"); }
